### ISSUE TITLE
.knsv files save paths as absolute, including the user's username

### ISSUE THREAD

**Issue by selplacei** [Prayag2/konsave#10]
Issue: exporting and importing profiles saves their absolute path relative to root, which means that imported profiles get extracted to the home directory of the same user that exported them. This pretty much defeats the point of sharing profiles between people or users.

Possible fix: save only the contents of the actual profile and derive its name from the name of the .knsv archive. Extract the profile to wherever Konsave keeps its configs on the given system, not to the same absolute path as the system that packaged it.

**Comment by Prayag2** [comment]
I'm working on the fix

**Comment by Prayag2** [comment]
Should be fixed in the latest release

**Comment by Prayag2** [comment]
Please let me know if it's working now
