### ISSUE TITLE
Failed apply after import

### ISSUE THREAD

**Issue by 1ter** [Prayag2/konsave#109]
**Describe the bug**
Exporting a profile in a Host PC and then applying .knsv after importing it in a Virtual Machine does fail. 

```
Konsave: Profile not found :(
Please check the log at /home/prova/.cache/konsave_log.txt for more details
```

This is `konsave_log.txt` (tried couple of times):

```
[08/05/2024 10:42:18]
Traceback (most recent call last):
  File "/home/prova/env/lib64/python3.6/site-packages/konsave/funcs.py", line 40, in inner_func
    function = func(*args, **kwargs)
  File "/home/prova/env/lib64/python3.6/site-packages/konsave/funcs.py", line 216, in apply_profile
    assert profile_name in profile_list, "Profile not found :("
AssertionError: Profile not found :(

[08/05/2024 10:42:56]
Traceback (most recent call last):
  File "/home/prova/env/lib64/python3.6/site-packages/konsave/funcs.py", line 40, in inner_func
    function = func(*args, **kwargs)
  File "/home/prova/env/lib64/python3.6/site-packages/konsave/funcs.py", line 216, in apply_profile
    assert profile_name in profile_list, "Profile not found :("
AssertionError: Profile not found :(

[08/05/2024 10:48:04]
Traceback (most recent call last):
  File "/home/prova/env/lib64/python3.6/site-packages/konsave/funcs.py", line 40, in inner_func
    function = func(*args, **kwargs)
  File "/home/prova/env/lib64/python3.6/site-packages/konsave/funcs.py", line 347, in import_profile
    ), "A profile with this name already exists"
AssertionError: A profile with this name already exists
```

**To reproduce**

**_Host (PC)_**
```
python3 -m venv env
source env/bin/activate
(env) pip install konsave
(env) konsave -s nickname
(env) konsave -e nickname
```

**_Target (VM)_**
```
python3 -m venv env
source env/bin/activate
(env) pip install konsave
(env) konsave -i nickname.knsv
(env) konsave -a 1
```

**Expected behavior**
Expected applying .knsv file succesfully.

**Screenshots**

**Host** (PC):
![image](https://github.com/Prayag2/konsave/assets/151228708/ad3d5872-f46c-4c20-822a-9c1d47c9f9e8)

**Target** (VM):
![image](https://github.com/Prayag2/konsave/assets/151228708/c3fd8ecc-a3ab-4ec7-a5f8-170628df863d)

**System information**
 - OS or Linux distribution: Kubuntu 23.10 (KDE Plasma 5.27.10)
 - How did you install Konsave? Using pip on both machines inside virtualenv
 - What version of Konsave are you using? 2.2.0 (on both source and target) Did you try updating? Why? I just installed right now on both, they are using last version available.

**Additional context**
What I was trying to do was exporting/importing between a Host and it's VM (virtualbox).
Target host is a VM with slightly different KDE plasma version and different distro (Opensuse Leap 15.5).

Source host: PC with Plasma ver. **5.27.10**
Target host: VM with Plasma ver. **5.27.9**

Both cases using virtual environment for python.

**Comment by Prayag2** [comment]
That's happening because IDs are no longer used to reference profiles. You refer to them using their names. So, in your case, you'll have to run these commands instead on your target machine-

```bash
python3 -m venv env
source env/bin/activate
(env) pip install konsave
(env) konsave -i nickname.knsv
(env) konsave -a nickname
```
Notice that I'm using `nickname` instead of `1` in the last command.
In the next release, you'll be able to use both, IDs and names to refer to profiles. (See https://github.com/Prayag2/konsave/issues/77)
