### ISSUE TITLE
konsave command not found

### ISSUE THREAD

**Issue by t3kg33k** [Prayag2/konsave#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

The install did not work for me.

![Selection_001](https://user-images.githubusercontent.com/4992046/109755777-a22b2b80-7bb4-11eb-86ee-eac0ffff7bc3.png)

I noticed in your script that the utility is placed in the ~/.local/bin/ path. The reason that it didn't work for me is because my path is defined differently in my environment.

PATH=/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/ed/bin

Maybe in your script you should either look at the user's PATH environment and place it in one of their defined paths or insert ./local/bin in the user's environment or something.
In the meantime, I will be adding that path to my .bashrc.

**Comment by t3kg33k** [comment]
To add:
After adding the path to my .bashrc on my desktop I was able to run it, save a profile and export. I then attempted to install konsave on my laptop (both desktop and laptop running Fedora 33 with KDE Plasma) but the bin directory didn't even exist in ~/.local/ so I had to manually create it and then install konsave then add that path to my .bashrc. I was then able to import.
So, again, there may need to be some adjustments to your install script to query and make adjustments based on the user's PATH environment.

**Comment by selplacei** [comment]
`$HOME/.local/bin` is expected to be in PATH on all XDG-compliant systems, and is the standard way to add an executable to a user's PATH. While it's not the responsibility of Konsave to change the user's .bashrc (especially since many people don't even use Bash), I agree that it would be nice to print as a message.

Also, if Konsave ever ends up on PyPI, it wouldn't need to manually create or link an executable in the first place.

**Comment by t3kg33k** [comment]
> `$HOME/.local/bin` is expected to be in PATH on all XDG-compliant systems, and is the standard way to add an executable to a user's PATH. While it's not the responsibility of Konsave to change the user's .bashrc (especially since many people don't even use Bash), I agree that it would be nice to print as a message.
> 
> Also, if Konsave ever ends up on PyPI, it wouldn't need to manually create or link an executable in the first place.

"...many people don't even use Bash"?
I'm confused by this statement. Who using Linux doesn't use Bash? I, and many, many others I know, use Bash on a daily basis.
Are you referring to the use of the Bash shell script to install the utility?

**Comment by selplacei** [comment]
> > `$HOME/.local/bin` is expected to be in PATH on all XDG-compliant systems, and is the standard way to add an executable to a user's PATH. While it's not the responsibility of Konsave to change the user's .bashrc (especially since many people don't even use Bash), I agree that it would be nice to print as a message.
> > Also, if Konsave ever ends up on PyPI, it wouldn't need to manually create or link an executable in the first place.
> 
> "...many people don't even use Bash"?
> I'm confused by this statement. Who using Linux doesn't use Bash? I, and many, many others I know, use Bash on a daily basis.
> Are you referring to the use of the Bash shell script to install the utility?

I'm referring to other shells that use a different .rc file and ignore .bashrc (zsh, fish, etc.)

**Comment by Prayag2** [comment]
With so many bugs present, I think I did a mistake with the versioning. Should I change the version to alpha?

**Comment by Prayag2** [comment]
Also @selplacei, please review look at this pull request and tell me your thoughts about it: https://github.com/Prayag2/konsave/pull/9

**Comment by selplacei** [comment]
> With so many bugs present, I think I did a mistake with the versioning. Should I change the version to alpha?

If you think that you've achieved the features you wanted so far, having a release is fine - bugfixes are released as patches. See [semantic versioning](https://semver.org/) for more info.

**Comment by selplacei** [comment]
> Also @selplacei, please look at this pull request and tell me your thoughts about it: #9

My version already has these features, so I'll leave it up to you to decide if you want them in your project. I'm here to fix things that I know how to fix.

**Comment by Prayag2** [comment]
Oh thanks

**Comment by Prayag2** [comment]
Should be fixed in the latest release

**Comment by Cabus1982** [comment]
`Dell% chmod +x ./install.sh

Dell% sudo ./install.sh 
[sudo] password for cperon: 
~~~~~~~~~~~~~~~~~~~~~~~~~~~
 _   ___  __
| | | \ \/ /      Prayag Jain | Hax Guru
| |_| |\  /       YouTube: https://youtube.com/c/haxguru
|  _  |/  \       GitHub: https://github.com/Prayag2
|_| |_/_/\_\      Email: prayagjain2@gmail.com

~~~~~~~~~~~~~~~~~~~~~~~~~~~
Installing konsave...
Installed successfully! You can now delete this folder.
Try 'konsave -h' for more info!

Dell% konsave -h
zsh: command not found: konsave

`

**Comment by t3kg33k** [comment]
> Should be fixed in the latest release

Awesome. I will try it out.

**Comment by t3kg33k** [comment]
So when you stated that "Should be fixed in the latest release", were you talking about this issue I opened? Or, something else?
The reason I ask is because it doesn't look as if you change the install script to correct the PATH environment variable issue. You are still assuming in that install script that everyone, every distribution, every shell, is going to have ~/.local/bin/ in their PATH, which is not always the case.

**Comment by Prayag2** [comment]
Tbh, I'm pretty new to this stuff (I'm just 17) and it's only been 5-6 months since I've started using Linux. I tried it in some VMs and it worked so I thought that it's fixed now. Please help me if you know a fix :)

**Comment by Prayag2** [comment]
I'm sorry, I wanted to delete my comment instead and I deleted yours by mistake. I'm soo sorry. But I finally learnt how to deploy it on PyPI and I'll do that ASAP! Thanks for helping me!

**Comment by Prayag2** [comment]
Finally. I've added it to PyPI!! Please delete the old konsave file by running `rm ~/.local/bin/konsave` to uninstall the old one and run `python -m pip install konsave` to install it from PyPI! Please let me know if it works for you now! I'm so excited hehe! Thanks for the help!!

**Comment by t3kg33k** [comment]
> Finally. I've added it to PyPI!! Please delete the old konsave file by running `rm ~/.local/bin/konsave` to uninstall the old one and run `python -m pip install konsave` to install it from PyPI! Please let me know if it works for you now! I'm so excited hehe! Thanks for the help!!

Nice work. The warning for the PATH is a good addition.
You can close this issue.

**Comment by Prayag2** [comment]
Thank you :)

**Comment by Prayag2** [comment]
Did you add it to PATH? Try running `~/.local/bin/konsave --help` and if that works, then it means that you have not added it to PATH.

**Comment by Kanishk598** [comment]
Thanks, added the line `export PATH="$HOME/.local/bin:$PATH"` at the end of my `.bashrc` file. Konsave is working now :)

**Comment by Prayag2** [comment]
Great :)
