### ISSUE TITLE
[Bug] Will not run in Ubuntu 24.04

### ISSUE THREAD

**Issue by bcook128** [Prayag2/konsave#110]
**Describe the bug**

Result of running konsave with ANY arguments:

Traceback (most recent call last):
  File "/home/brad/.local/bin/konsave", line 5, in <module>
    from konsave.__main__ import main
  File "/home/brad/.local/share/pipx/venvs/konsave/lib/python3.12/site-packages/konsave/__init__.py", line 3, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

System:
Ubuntu 24.04

Python version:
Python 3.12.3

konsave Version:
konsave 2.2.0

Setuptools Version:
setuptools 68.1.2

Installed via pipx

**Comment by hueyy** [comment]
Could this be related to https://github.com/Prayag2/konsave/issues/99?

**Comment by Prayag2** [comment]
`pkg_resources` has been deprecated and I haven't got the time to update it. I'll fix this in the next release, until then, you may install `setuptools` to fix this issue:

On Arch:
`sudo pacman -S python-setuptools`

Using Pip
`pip install setuptools`

**Comment by paulo-roger** [comment]
Same error in Garuda Linux.

All the same versions and output from OP here too.

**Comment by tazmo** [comment]
Unfortunately installing python3-setuptools in Ubuntu 24.04 does not appear to fix it.

**Comment by bcook128** [comment]
> Unfortunately installing python3-setuptools in Ubuntu 24.04 does not appear to fix it.

Anything later than Ubuntu 22.04 doesn't like pip. You most likely installed konsave with pipx so you'll have to "pipx inject konsave setuptools" to install into the konsave virtual environment. That should make it available for konsave to use and fix the issue in 24.04

**Comment by tazmo** [comment]
Exactly @bcook128. I should have added using pipx to my comment above... I am using pipx on 24.04 and after doing the "pipx inject konsave setuptools", that worked for Ubuntu 24.04. konsave seems to work now (for me). Thank you for the response.

**Comment by youngstroker** [comment]
> Exactly @bcook128. I should have added using pipx to my comment above... I am using pipx on 24.04 and after doing the "pipx inject konsave setuptools", that worked for Ubuntu 24.04. konsave seems to work now (for me). Thank you for the response.

Can confirm, this does work for now, thank you.

**Comment by giammyisjammy** [comment]
> Anything later than Ubuntu 22.04 doesn't like pip. You most likely installed konsave with pipx so you'll have to "pipx inject konsave setuptools" to install into the konsave virtual environment. That should make it available for konsave to use and fix the issue in 24.04

Can confirm it worked for me on Ubuntu 24.04 LTS. Should this be added to the README.md under Installation?
