### ISSUE TITLE
[Feature Request] General Desktop environment support

### ISSUE THREAD

**Issue by jason-mehmel** [Prayag2/konsave#115]
**Is your feature request related to a problem? Please describe.**

I was hoping for Konsave to solve my issue of exporting all of my configs from one machine to another... but discovering that it doesn't capture any environment info on first running (if not Plasma) I realized I'd have to manually add all the files and folders I'd want to capture, nearly as much work as collecting and copying them anyway.

**Describe the solution you'd like**
Running Konsave would collect info from most Linux systems, Debian, Ubuntu, etc. (I'm running a Debian variant, BunsenLabs.) Capturing configs from Plasma, Gnome, Openbox, etc.

**Describe alternatives you've considered**
The only other solution is making a list of what programs and tools I want to remember to install on the new machine, plus copying the config dotfiles in their respective locations.

**Additional context**

**Comment by Prayag2** [comment]
What desktop environment are you on? Konsave does capture configs by default, but only on KDE Plasma.

**Comment by jason-mehmel** [comment]
Bunsenlabs is my distro, and it's DE is Openbox, I believe!

**Comment by Prayag2** [comment]
For all environments other than KDE Plasma, you have to manually add the files to backup in the config. But that is to be done only once, as a one-time setup.
