### ISSUE TITLE
konsave apply error

### ISSUE THREAD

**Issue by t3kg33k** [Prayag2/konsave#13]
**Describe the bug**

**To reproduce**
Steps to reproduce the behavior. [click this, type that, see error]

**Expected behavior**

**Screenshots**

**System information**
 - OS or Linux distribution: [Ubuntu, Arch, ...]
 - How did you install Konsave? [from the distro's package manager, using pip, directly from git, ...]
 - What version of Konsave are you using? Did you try updating?

**Additional context**

Applying an import from my desktop to my laptop I get this error message:

Konsave: [Errno 2] No such file or directory: '/home/ed/.config/konsave/profilesedded/'

![Selection_001](https://user-images.githubusercontent.com/4992046/110144152-03feb780-7da6-11eb-9915-d402410012d6.png)

I'm using Fedora 33 on both machines. Both running Plasma 5.20.5.

**Comment by Prayag2** [comment]
What python version are you using?

**Comment by t3kg33k** [comment]
3.9.2

**Comment by Prayag2** [comment]
Could you please try running the following:
`python`
`import os`
`os.path.join("/home/ed/.config/konsave/profiles", "edded")`
I want you to run this because I don't know why is it happening. It works for me and everyone just fine

**Comment by t3kg33k** [comment]
>>> import os
>>> os.path.join("/home/ed/.config/konsave/profiles", "edded")
'/home/ed/.config/konsave/profiles/edded'

**Comment by Prayag2** [comment]
hmm okay. I still don't understand why is it happening to you but could you please try removing the "konsave" directory from "~/.config/konsave" and try importing your config again?

**Comment by t3kg33k** [comment]
Still a problem.

![Selection_002](https://user-images.githubusercontent.com/4992046/110157523-429c6e00-7db6-11eb-84c1-4e1b53e3a731.png)

**Comment by selplacei** [comment]
Please fill out the bug report template as intended. What version of Konsave are you using? Is it up to date?

**Comment by t3kg33k** [comment]
Will do:

Describe the bug
Applying an import from my desktop to my laptop I get this error message:

Konsave: [Errno 2] No such file or directory: '/home/ed/.config/konsave/profilesedded/'

To reproduce
Ran: konsave -a <id>

Expected behavior
Expected it to apply the profile I had exported from my desktop and imported to my laptop

Screenshots
Added

System information

    OS or Linux distribution: [Ubuntu, Arch, ...] Fedora 33
    How did you install Konsave? [from the distro's package manager, using pip, directly from git, ...] Originally, from install shell script on my desktop and laptop then PyPi from desktop.
    What version of Konsave are you using? Did you try updating? Unsure what version as there is no argument to tell me what version I am running. I will try to install via PyPi on my laptop to see if it updates.

**Comment by t3kg33k** [comment]
Installed again on my laptop via PyPi and that seemed to have fixed it. I'm assuming that updated konsave.
I would recommend adding an argument (e.g. -v --version) that shows what version is installed.
Nice work on this. Having recently moved from Gnome to try out KDE I think I will stay awhile since this tool exist.
Keep up the good work.
You can close this issue.

**Comment by Prayag2** [comment]
Thanks :)
