### ISSUE TITLE
Support Python >=3.7

### ISSUE THREAD

**Issue by majabojarska** [Prayag2/konsave#17]
Konsave's README declares that the minimal required Python version "above 3.9". I'm guessing @Prayag2 meant "at least 3.9", since 3.10 is [not released yet](https://www.python.org/dev/peps/pep-0619/). 

My question is, what causes this requirement? Correct me if I'm wrong, but it seems like Konsave could run even on `>=3.6`. Requiring such narrow (and recent) version range limits the availability for people who don't use Python `>=3.9`. The package does not enforce a specific Python version (e.g. via setuptools), so fortunately it's still possible to install Konsave in environments with earlier Python versions.

I propose to expand the supported Python version range to `>=3.7` and enforce it via [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires).

**Comment by Prayag2** [comment]
Done in the latest commit!

**Comment by majabojarska** [comment]
Great, thank you!
