### ISSUE TITLE
Introduce project guidelines: code style, docstring style, formatter, linter, etc.

### ISSUE THREAD

**Issue by majabojarska** [Prayag2/konsave#20]
As this little project is gaining traction, it would be good to introduce code guidelines. Specifically docstring style, formatting and linting tools. Everyone has some coding habits and prefers some tools over other. However, in a project it would be best to agree on some rules, just to keep the codebase clean and uniform.

This is obviously a topic for discussion. From my side, I'd like to propose the following:
- [PEP8](https://www.python.org/dev/peps/pep-0008/) code style, as it's the official Python style guide. To check for code style compliance, a linter should be used, such as [Flake8](https://flake8.pycqa.org/en/latest/) or [Pylint](https://www.pylint.org/). Both check the code against PEP8. Pylint is stricter, but also more elastic. Both Flake8 and Pylint can be tweaked if necessary. I would go with Pylint after all.
- [Black](https://github.com/psf/black) formatter, as it is PEP8-compliant and has sensible defaults. It can be run also as a [pre-commit](https://pre-commit.com/) Git hook to format the codebase on commit. Integrates well with various editors and IDEs.
- [Numpy docstring style](https://numpydoc.readthedocs.io/en/latest/format.html). It's pretty common and well supported. Can be paired with [Darglint](https://github.com/terrencepreilly/darglint) to lint docstrings.

The above guidelines can be later described via a `CONTRIBUTING.md` file together with the preferred contributing workflow.

**Comment by Prayag2** [comment]
OOOOHHHH this is awesome! I didn't know about any of these! The last one is really amazing! I never knew that I needed it so much! Thank you!! I learnt a lot from you!

**Comment by Prayag2** [comment]
Please have a look at https://github.com/Prayag2/konsave/pull/27

**Comment by majabojarska** [comment]
#27 Is already merged. I left some feedback over there.

**Comment by majabojarska** [comment]
Added Black and PyLint as dev requirements in #30.
