### ISSUE TITLE
python3+ support 

### ISSUE THREAD

**Issue by luizoti** [Prayag2/konsave#21]
**Describe the bug**
Konsave supports only python 3.8+

**To reproduce**
Steps to reproduce the behavior. [click this, type that, see error]
`konsave -a 1`

**Expected behavior**
Apply config

**Screenshots**
[Image](https://i.imgur.com/EJGboT8.png)

**System information**
 - OS or Linux distribution: 
 Kubuntu 18.04
 - How did you install Konsave?
 pip
 - What version of Konsave are you using? Did you try updating?
 Konsave: 1.1.3

**Additional context**

I receve this error when i try to apply config:
`Konsave: copytree() got an unexpected keyword argument 'dirs_exist_ok'`

On shutil docs i found this note:
`New in version 3.8: The dirs_exist_ok parameter.`

Perhaps an internal copy module for konsave needs to be created, this may solve compatibility problems.

**Comment by Prayag2** [comment]
Should be fixed in https://github.com/Prayag2/konsave/pull/23
