### ISSUE TITLE
Export leads to error

### ISSUE THREAD

**Issue by mmahmoudian** [Prayag2/konsave#28]
### Describe the bug
Exporting profile leads to error and despite of getting the message that "Konsave: Successfully exported to ..." the `.knsv` file is not created.

### To reproduce
```sh
❯  konsave --save "My_KDE_profile"
```
> ```
> Konsave: Saving profile...
> Konsave: Profile saved successfully!
> ```

```sh
❯  konsave --list
```
> ```
> Konsave profiles:
> ID      NAME
> 1       My_KDE_profile
> ```

```sh
❯  konsave --save "My_KDE_profile"
```
> ```
> Konsave: Profile with this name already exists
> Try 'konsave -h' for more info!
> ```

```sh
❯  konsave --export-profile 1
```
> ```
> Konsave: Exporting profile. it might take a minute or two...
> Konsave: 'Mouse'
> Try 'konsave -h' for more info!
> Konsave: Exporting icon theme
> Konsave: [Errno 2] No such file or directory: '/usr/share/icons/breath2-dark/actions/16/view-financial-account-> asset.svg'
> Try 'konsave -h' for more info!
> Konsave: [Errno 2] No such file or directory: '/usr/share/icons/breath2-dark/actions/16@2x/view-financial-account-> asset.svg'
> Try 'konsave -h' for more info!
> Konsave: Exporting plasma files
> Konsave: Source path doesn't exist
> Try 'konsave -h' for more info!
> Konsave: Exporting config files
> Konsave: Creating archive
> Konsave: Successfully exported to /home/mehrad/my_kde_profile.knsv
> ```

which cause ErrorCode: 130

```sh
❯  ls -al /home/mehrad/my_kde_profile.knsv
```
> ```
> ls: cannot access '/home/mehrad/my_kde_profile.knsv': No such file or directory
> ```

```sh
❯  konsave --version
```
> ```
> Konsave: 1.1.6
> ```

### Expected behavior
No error, and having the `.knsv` output file.

### Screenshots
-- Not Applicable. --

### System information
 - OS or Linux distribution:
     - > ```sh
       > ❯ inxi --width 80 --system --graphics
       > ```
       > ```
       > System:
       >   Host: Chrstphr Kernel: 5.11.2-1-MANJARO x86_64 bits: 64
       >   Desktop: KDE Plasma 5.21.2 Distro: Manjaro Linux
       > Graphics:
       >   Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics
       >   driver: i915 v: kernel
       >   Device-2: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 460.56
       >   Display: x11 server: X.Org 1.20.10 driver: loaded: modesetting,nvidia
       >   unloaded: nouveau resolution: 1: 1080x1920~60Hz 2: 1080x1920~60Hz
       >   3: 1920x1080~60Hz
       >   OpenGL: renderer: GeForce GTX 1060 6GB/PCIe/SSE2 v: 4.6.0 NVIDIA 460.56
       > ```
 - How did you install Konsave? [from the distro's package manager, using pip, directly from git, ...]
     - >```sh
       > ❯  pamac search konsave
       > ```
       > ```
       > konsave                                                                  [Installed] 1.1.6-1  AUR
       > Save and apply your KDE Plasma customizations with just one command!
       > ```
 - What version of Konsave are you using? Did you try updating?
     - The 1.1.6 is the latest at this moment.

**Comment by Prayag2** [comment]
Please try using the `PyPI` version instead. The AUR package is not officially supported. Run `python -m pip install konsave` to install it using pip and let me know if it works!

**Comment by Prayag2** [comment]
You can still import the file in other machines as long as they have the same icon pack installed. It seems to be an issue only with the breath2 icon pack. I'll try fixing it ASAP.

**Comment by mmahmoudian** [comment]
@Prayag2 Although the konsave says:

> ```
> Konsave: Successfully exported to /home/mehrad/my_kde_profile.knsv
> ```

The file is never created:

> ```
> ls: cannot access '/home/mehrad/my_kde_profile.knsv': No such file or directory
> ```

Do you mean that Konsave has crashed because the breath2 icon pack?

**Comment by Prayag2** [comment]
Should be fixed in the latest release `1.1.7`. Please use `PyPI` to install the latest version. Enter `python -m pip install konsave` to install it! Make sure to remove the AUR version first.

**Comment by Prayag2** [comment]
Please let me know if the latest release works for you.

**Comment by mmahmoudian** [comment]
Sorry, I'm not a big fan of installing through pip (or cargo) as they tend to break more frequently than normal. I perhaps wait until 1.1.9 is in the repo and also the following issue is fixed:


For now, I have version 1.1.8 and I get:
> ```
> pkg_resources.ContextualVersionConflict: (PyYAML 5.3.1 (/usr/lib/python3.9/site-packages), Requirement.parse('PyYaml==5.4.1'), {'Konsave'})
> ```
which, as far as I understand, it seems you have used a python library that is not released in Manjaro or Arch:
https://archlinux.org/packages/community/x86_64/python-yaml/

Is it possible to either use library versions that are at leased in the repo of rolling release distros?

-------

Just as an explanation, AUR literally uses your `setup.py` to build and then install:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=konsave

The AUR itself just installs dependencies.

**Comment by dbro86** [comment]
@mmahmoudian the package `python-yaml` has been updated to 5.4.1.1 yesterday. Only after that I updated the AUR package.

**Comment by mmahmoudian** [comment]
@dbro86 it seems at least it is not yet updates on Manjaro mirrors:

![image](https://user-images.githubusercontent.com/390889/111669794-d2fb9980-881f-11eb-86c5-44682c6ce965.png)

**Comment by Prayag2** [comment]
Please check the latest version of Konsave. It has changed a lot! Make sure to remove the old `conf.yaml` and profiles from `~/.config/konsave/` as they are incompatible with the new version of Konsave.

**Comment by mmahmoudian** [comment]
I just tested it (v2.0.2) and it worked. Thanks.
