### ISSUE TITLE
Issues with saving configurations.

### ISSUE THREAD

**Issue by ben2talk** [Prayag2/konsave#31]
**Is your feature request related to a problem? Please describe.**
Playing with PlasmaConfigSaver, also consave/konsave/konfsave there are issues.

1. We need options for simpler 'GlobalTheme' style saving which won't backup Latte unless something is specifically included. For example, I set up a 'Gruv' profile - latte and event calendar and saved it.
2. Set up Nord, new tweaks to event calendar, modified and backed up the latte style.
3. restored 'Gruv' and lost the changes to the event calendar.

I think an informative configuration file with lines to include/exclude is good.
e.g.
OPTIONS # save as global theme # include plasma style and colours, decorations, fonts # save complete plasma config # Save Konsole profile

Currently I have regular timeshift backups, though I'm interested to try different workflow ideas.
So I would like to do profiles like....
1. Dark-Gruv Plasma
2. Dark-Gruv Theme
3. Nord Plasma
4. Nord Theme

I hope it makes some sense. Right now if I do any modification to my 'Gruv' that I want to also include in my 'Library' and 'Nord' profiles, it's not easy to do... it's duplicating the effort.

The most useful task this software could manage IMO would be to create a Global Theme which can appear in the Plasma settings applet.

**Comment by Prayag2** [comment]
Please check the latest version of Konsave. Make sure to remove the old `conf.yaml` and profiles from `~/.config/konsave/` as they are incompatible with the new versions of konsave.
