### ISSUE TITLE
Make saving configuration easier

### ISSUE THREAD

**Issue by qx-775** [Prayag2/konsave#38]
I love your tool. This is what I needed to save _all_ plasma settings!

To export it to a file first you have to save a configuruation with a name and then export it. However it exports it to ~/.knsv
I want it to immediately export it to my current directory, for example my dotfiles. 

Can you make it easier to save the configuration for backup purposes for example to use `konsave -e mybackup.knsv` ?
Which automatically makes a backup, zips and saves to a directory (or the current directory) 

Understood me? Thank you!

**Comment by Prayag2** [comment]
I'm sorry but could you please clarify?

**Comment by Delvien** [comment]
konsave -e <profile number> is how you export profiles, the knsv file is named based on your profile name.

Saving configurations are very easy, please read before you suggest a change. (type konsave in a terminal)

**Comment by qx-775** [comment]
Let me try to clarify.

What I mean is that I want a easier way to save the settings without making a profile. Let's say the use case is that the user just wants to save all the settings to a file. No need to make a profile right? Let's say there's an option `konsave backupplasmasettings.knsv` which automatically creates such a file with the zip file of all settings. Currently it saves profiles to ~/.ID.knsv which I want to avoid. This makes it easier to create a backup and there's no need to understand how the process currently works:

`konsave -s to save to profile` --> `konsave -l to get the id of the named profile` --> `konsave -e ID` --> `copy the ~/.ID.knsv to a different directory`  -> `done`

I want to change the workflow to this:
`konsave -s konsavebackup` -> `konsave generated a konsavebackup.knsv in the current directory` thus no need for a profile generation.

The problem with making a profile is that I had to figure out first what their ID was and not their name in order to export it. Ofcourse `konsave -l` shows the name and id, but it's a hassle.  

Also maybe give an example of most used konsave command line usages in the --help flag. I think argparse can give extra info on command line usage. This would help users who just started to use this tool.

And yes ofcourse I have read the documentation.

**Comment by Prayag2** [comment]
That would be a nice feature I think. I'll add it to my to-do list.

**Comment by Qussayyon** [comment]
> Let me try to clarify.
> 
> What I mean is that I want a easier way to save the settings without making a profile. Let's say the use case is that the user just wants to save all the settings to a file. No need to make a profile right? Let's say there's an option `konsave backupplasmasettings.knsv` which automatically creates such a file with the zip file of all settings. Currently it saves profiles to ~/.ID.knsv which I want to avoid. This makes it easier to create a backup and there's no need to understand how the process currently works:
> 
> `konsave -s to save to profile` --> `konsave -l to get the id of the named profile` --> `konsave -e ID` --> `copy the ~/.ID.knsv to a different directory` -> `done`
> 
> I want to change the workflow to this:
> `konsave -s konsavebackup` -> `konsave generated a konsavebackup.knsv in the current directory` thus no need for a profile generation.
> 
> The problem with making a profile is that I had to figure out first what their ID was and not their name in order to export it. Ofcourse `konsave -l` shows the name and id, but it's a hassle.
> 
> Also maybe give an example of most used konsave command line usages in the --help flag. I think argparse can give extra info on command line usage. This would help users who just started to use this tool.
> 
> And yes ofcourse I have read the documentation.

@Prayag2 
Maybe after first step: ```konsave -s to save to profile``` you may execute ```konsave -l``` on behave of user and also tell user to use ```konsave -e ID``` to export the profile.

Also, I think it's good idea to put the script in directory ```~/bin``` and not ```~/.local/bin```, what do U think?

**Comment by Prayag2** [comment]
I'm sorry I'm very late. I had my exams. Anyways, I have made saving configurations easier. Please look at https://github.com/Prayag2/konsave/pull/43

You'll now be able to export, remove and apply profiles using their names!

**Comment by qx-775** [comment]
Nice dude! Hope ur exams went well! Feel free to close this issue if you deem your PR request sufficient. Looks good to me.

**Comment by Prayag2** [comment]
Thanks!
