### ISSUE TITLE
Import doesn't seem to work in a fresh os install

### ISSUE THREAD

**Issue by ghost** [Prayag2/konsave#39]
I created and saved a profile in a previous installation. I had to reinstall whole OS again and I tried to import the profile I created before but it fails:

```bash
konsave -i ~/.nextcloud/dotfiles/portatil/fedora-konsave.knsv 
Konsave: Importing profile. it might take a minute or two...
Konsave: [Errno 2] No such file or directory: '/home/user/.config/konsave/temp/fedora-konsave/conf.yaml'
Please check the log at /home/user/konsave_log.txt for more details.
Konsave: Source path doesn't exist
Please check the log at /home/user/konsave_log.txt for more details.
Konsave: [Errno 2] No such file or directory: '/home/user/.config/konsave/temp/fedora-konsave/conf.yaml'
Please check the log at /home/user/konsave_log.txt for more details.
```
Here's the log:

[konsave_log.txt](https://github.com/Prayag2/konsave/files/6445673/konsave_log.txt)

**Comment by Prayag2** [comment]
Can you share the output of the following:
`ls ~/.config/konsave/temp`
Also, please tell me which version of Konsave were you using before and which version are you using now?

**Comment by Neules** [comment]
```bash
ls ~/.config/konsave/temp/
fedora-konsave
```

I don't know which version I was using. I installed it 2 weeks ago or so...

Current version is the last (installed yesterday I think):

```bash
konsave -v
Konsave: 2.0.2
```

**Comment by thespyboss** [comment]
I downgraded to 1.1.9 and it worked on both ends. The profile has to be made and exported through 1.1.9 and then the receiving end has to also be 1.1.9

**Comment by Prayag2** [comment]
Yes. Versions 2.X.X are incompatible with the old versions of Konsave as mentioned in the [changelog](https://github.com/Prayag2/konsave/blob/master/CHANGELOG.md#200---2021-04-11). I think I can close this issue now?

**Comment by Prayag2** [comment]
No worries mate. You are free to open issues whenever you want!
