### ISSUE TITLE
Config Shenanigans

### ISSUE THREAD

**Issue by ben2talk** [Prayag2/konsave#4]
Playing with this - loving it... despite the error mentioned in the other issue.

Initially for one LIGHT and one DARK config.
1. Set Global theme (Breeze) plasma (breeze with transparency) 
2. Application style (kvantum - transparent Dolphin, Darkish one edited from Flatblur-Manjaro)
3. Set personal colours (Grey-green combination)
4. IMPORTANT - set DEFAULT Konsole colour to Darkish profile
5. Run `consave -s Dark && consave -l` to check.
6. repeat for a lighter theme.

To ensure Dolphin got refreshed, I decided to kill that on change and latte definitely needs a refresh if you run that.

```
#!/bin/bash
consave -a 1
latte-dock --replace &&
plasmashell --replace &&

if pgrep -x "dolphin"
    then pkill dolphin
fi
```
Make one script for each profile (1 is Dark, 2 is Light) and that's about it. 

If anything else is dodgy, it's fixed by doing `kwin_x11 --replace`

**Comment by Prayag2** [comment]
What exactly is the issue?

**Comment by ben2talk** [comment]
Apologies - just that there's no real need to log out/in again. It's all good now.
