### ISSUE TITLE
Wallpaper not saved

### ISSUE THREAD

**Issue by Xelibix** [Prayag2/konsave#40]
I reinstalled my system and imported my saved configuration.
All parameters are ok except the wallpaper that wasn't restored.
Maybe it does not backup the wallpaper image.

**Comment by Prayag2** [comment]
Yes, the wallpaper is not exported by default. You have to specify the location of your wallpaper manually in the config file of your profile (`~/.config/konsave/profiles/<your-profile>/conf.yaml`). I can try to make it back up the wallpaper in the future but I don't have time right now.

**Comment by Xelibix** [comment]
ok thx
