### ISSUE TITLE
Original theme isnt completely restored

### ISSUE THREAD

**Issue by benjamimgois** [Prayag2/konsave#41]
**Describe the bug**
First of all, congratulations on your work ! Konsave seems like the perfect tool i was looking for. I'm having a little trouble using it. The original theme isn't completely restored by konsave for me.

**To reproduce**

- Save the original theme to konsave with `konsave -s manjaro`
- Install the new theme (used https://github.com/vinceliuice/WhiteSur-kde)
- Apply the new theme 
- Save the new desktop with `konsave -s sur`
- Restore the original theme with `konsave -a 1`

**Expected behavior**
The original theme being completely restored.

**Screenshots**
Original theme
<a href="https://ibb.co/KG3bS1q"><img src="https://i.ibb.co/sPMbzBw/manjaro1.png" alt="manjaro1" border="0"></a><br /><a target='_blank' href='https://pt-br.imgbb.com/'>imagem qualquer</a><br />

The original theme restored
<a href="https://ibb.co/NNypSWB"><img src="https://i.ibb.co/ykQ5Sgj/manjaro2.png" alt="manjaro2" border="0"></a>

**System information**
 - Manjaro 21.1.1
 - Konsave installed from distro repository
 - Konsave version 2.0.2-1

**Additional context**
I would like to create a GUI for konsave, but before i start to work i would like to se it working properly.

**Comment by Prayag2** [comment]
Thanks for the kind words! Have you tried restarting KDE Plasma after restoring a profile? You can also try logging out and then logging in.

**Comment by benjamimgois** [comment]
> Thanks for the kind words! Have you tried restarting KDE Plasma after restoring a profile? You can also try logging out and then logging in.

Yes, i did. The last print is after restarting the desktop.

**Comment by benjamimgois** [comment]
Just to let you know. I wish to create a GUI similar to gnome-layout-switcher from Manjaro Gnome, but using konsave as a base.

<a href="https://ibb.co/Nx91JKT"><img src="https://i.ibb.co/2qv8CdZ/fb576ea3bc7617eb95a647ce1a52a1a726d5e5b5.jpg" alt="fb576ea3bc7617eb95a647ce1a52a1a726d5e5b5" border="0"></a>

**Comment by Prayag2** [comment]
> Yes, i did. The last print is after restarting the desktop.  

Oh. Can you show me the contents of your config file? It is located in `~/.config/konsave/profiles/<your-profile>/conf.yaml`.  
> Just to let you know. I wish to create a GUI similar to gnome-layout-switcher from Manjaro Gnome, but using konsave as a base.

That's an amazing idea! I'd love to help but my exams are near so I don't have time :(

**Comment by benjamimgois** [comment]
> Oh. Can you show me the contents of your config file? It is located in `~/.config/konsave/profiles/<your-profile>/conf.yaml`.

Sure, here is my conf.yaml

[conf.yaml.txt](https://github.com/Prayag2/konsave/files/7106405/conf.yaml.txt)

**Comment by Prayag2** [comment]
Please remove the `.txt` from the name of the config file and try again.

**Comment by benjamimgois** [comment]
@Prayag2 i put the .txt just to upload it here on github. On the directory it's just yaml.

**Comment by benjamimgois** [comment]
I just found some clue. I was using a dual monitor setup. After i change to a single monitor, it seems to work much better now. Almost everything is restored perfectly. I'll keep investigating, if that is the reason i'll close the bug.

**Comment by Prayag2** [comment]
Ok. I don't have a dual monitor setup so I don't know why is it happening but you can help me improve Konsave! That's what I love about open source software!

**Comment by benjamimgois** [comment]
Hi @Prayag2 , sorry for tooking so long. Indeed using a single monitor fix the issue with konsave. I just have one small "problem" i wanted to point. The only thing that isn't correctly restored is the icon of the applications launcher. It should be the manjaro distro logo, instead it's using the stock plasma icon. It's not a big deal, but i just wanted to point it out. 

![restored_manjaro](https://user-images.githubusercontent.com/7688496/132853336-89fa36a3-c1a3-4cf8-877c-d99acf3e517f.png)

Thanks for this amazing app. I'll let you know soon of the app development.

**Comment by Prayag2** [comment]
Konsave works by backing up config files. If you know which config file stores the location of this icon, please let me know! I'll add it ASAP.
