### ISSUE TITLE
does not apply (at all) or save profile properly

### ISSUE THREAD

**Issue by x-crowbar-x** [Prayag2/konsave#49]
I use KDE Plasma 5.23.4 (on Arch Linux). Maybe this is the reason, idk.
Technically, it saves the profile, but it prints this into terminal: 
`Konsave: Saving profile...
Konsave: 'NoneType' object is not iterable
Please check the log at /home/crowbar/konsave_log.txt for more details.`

And this is from the log:
`Traceback (most recent call last):
  File "/home/crowbar/.local/lib/python3.9/site-packages/konsave/funcs.py", line 40, in inner_func
    function = func(*args, **kwargs)
  File "/home/crowbar/.local/lib/python3.9/site-packages/konsave/funcs.py", line 176, in save_profile
    for entry in konsave_config[section]["entries"]:
TypeError: 'NoneType' object is not iterable`

I tried to apply the theme and it said that it was applied, but nothing changed even after restart.

**Comment by Prayag2** [comment]
Did you change anything in the config file (`~/.config/konsave/conf.yaml`)?

**Comment by x-crowbar-x** [comment]
@Prayag2 no, nothing

**Comment by Prayag2** [comment]
Please paste the contents of that file.

**Comment by x-crowbar-x** [comment]
---
# This is the configuration file for konsave.
# Please make sure it follows the correct format for proper working of konsave.
# The format should be:
# ---
# save:
#     name:
#         location: "path/to/parent/directory"
#         entries: 
#         # these are files to be backed up. They should be present in the specified location.
#             - file1
#             - file2
# export:
#     # This includes files which will be exported with your profile.
#     # They will not be saved but only be exported and imported.
#     # These may include files like complete icon packs and themes..
#     name:
#         location: "path/to/parent/directory"
#         entries: 
#             - file1
#             - file2
# ...
# You can use these variables and functions in the locations of different entries:
# $HOME: the home directory
# $PROFILES_DIR: directory where all profiles are saved
# $CONFIG_DIR: refers to "$HOME/.config/"
# $KONSAVE_DIR: the location where all Konsave files are stored ("$CONFIG_DIR/konsave").
# ${ENDS_WITH="text"}: for folders with different names on different computers but their names end with the same thing.
# The best example for this is the ".default-release" folder for firefox.
# ${BEGINS_WITH="text"}: for folders with different names on different computers but their names start with the same thing.

# The following files will be saved in your profiles
save:
    configs:
        location: "$HOME/.config"
        entries:
            # add config files and folders to backup here like this
            # - file1
            # - file2
            # - folder1

    # Here are a few examples of how you can add more stuff to back up
    # firefox:
    #     location: "$HOME/.mozilla/firefox/${ENDS_WITH='.default-release'}"
    #     entries:
    #         - chrome # for firefox customizations

    # oss:
    #     location: "$HOME/.config/Code - OSS/User/"
    #     entries:
    #         - settings.json


# The following files will only be used for exporting and importing.
export:
    share_folder:
        location: "$HOME/.local/share"
        entries:
            # add files/folders to export from "~/.local/share" here
    home_folder:
        location: "$HOME/"
        entries:
            # add files/folders to export from the home directory here
    
    # You can add more files to export like this
    # name:
        # location: "path"
        # entries:
            # - file1
            # - file2
            # - folder1
            # - folder2

**Comment by Prayag2** [comment]
This is an empty config file meant for other desktop environments. It seems like Konsave didn't detect your desktop environment properly. Please delete this config file and run Konsave again. It will surely fix it. If it doesn't please let me know! Did you by any chance run `konsave` in a desktop environment other than KDE?

**Comment by x-crowbar-x** [comment]
Thanks a lot! It was saved successfully. I haven't applied it yet, but I will try soon and if anything goes wrong, I'll let you know. For now, I guess, it can be closed. 

No, I use only KDE now, and when I used other DEs, I didn't know that this tool existed)

**Comment by Prayag2** [comment]
Just for debugging purposes, can you let me know the output of `echo $XDG_CURRENT_DESKTOP`?

**Comment by x-crowbar-x** [comment]
[crowbar@lenovo ~]$ echo $XDG_CURRENT_DESKTOP
KDE

**Comment by Prayag2** [comment]
Okay, thanks!
