### ISSUE TITLE
Make konsave a PyPI-ready package

### ISSUE THREAD

**Issue by majabojarska** [Prayag2/konsave#5]
Deploying to [PyPI](https://pypi.org/) would simplify the install process and improve the availability of this tool.
This will also facilitate future, distro-specific adoption of this tool (e.g. on [AUR](https://aur.archlinux.org/)).

I'm willing to make the necessary improvements soon:
- Wrap the existing code in a setuptools-based package that can be deployed to PyPI.
- Create GitHub Actions workflow for automatic deployment when a tag is pushed.
- ~~Some basic unit tests to run before deployment (?).~~

Creating this issue as a heads up that I'll be working on this :wink:. Please leave your suggestions on this topic in the comments below.

**Comment by Prayag2** [comment]
Great idea! I've been thinking about deploying it PyPI too! Your help will be very much appreciated :)

**Comment by majabojarska** [comment]
@Prayag2 can you state the reason for closing this issue?

**Comment by Prayag2** [comment]
I'm sorry I thought there was no reason for it to be kept open. I'll reopen it!

**Comment by majabojarska** [comment]
Thanks. I'm currently busy with work and personal matters, but I'll make the necessary changes by the weekend.

**Comment by Prayag2** [comment]
FINALLY!! I've DEPLOYED IT TO PYPI!! Please check it out!

**Comment by majabojarska** [comment]
That's great! Good job :smile_cat:.
