### ISSUE TITLE
konsave --diff

### ISSUE THREAD

**Issue by MenacingPerson** [Prayag2/konsave#52]
**Is your feature request related to a problem? Please describe.**
Maybe it should have this, so you can differentiate between your saved .knsv and your current config

**Describe the solution you'd like**
`konsave -d <file>.knsv`

**Describe alternatives you've considered**

**Additional context**

**Comment by Prayag2** [comment]
Can you please elaborate? Maybe I can make it so that it will take a screenshot of the desktop everytime you save a configuration?

**Comment by Samisafool** [comment]
It would show what the difference in files is, sort of like `git diff` or the `diff` tool.

**Comment by Sarke** [comment]
Like this?

```bash
git diff --no-index ~/.config/konsave/profiles/prof1 ~/.config/konsave/profiles/prof2
```

It would be nice if it had an option that was aware of the different settings, so you could pick what to apply, but that's a big ask.

**Comment by Samisafool** [comment]
> Like this?
> 
> ```
> git diff --no-index ~/.config/konsave/profiles/prof1 ~/.config/konsave/profiles/prof2
> ```

> It would be nice if it had an option that was aware of the different settings, so you could pick what to apply, but that's a big ask.

No, I mean one that diffs between the current, live config, and any saved profile.

**Comment by Sarke** [comment]
So just save the current one.

**Comment by Prayag2** [comment]
The best I can do right now (I have exams so I don't have much time) is that every profile is going to have a screenshot so you can compare how different profiles look like. To be able to tell the difference between the profiles is a very big task and I would have to make Konsave specific to KDE Plasma for that (it works on all DEs right now as a simple config backup tool).
