### ISSUE TITLE
Thank you for making this!

### ISSUE THREAD

**Issue by MichaelTunnell** [Prayag2/konsave#6]
Hey @Prayag2, thank you so much for taking the time to make this! :sunglasses:

This is something I've wanted to see for quite a while and I even discussed this concept on a recent [episode of Destination Linux podcast](https://youtu.be/4ElGuRG7kdQ?t=1742) so as you can imagine I was very excited to see it being made less than a week after talking about it on the show. :D I'm not sure if you are familiar with the show or not but either way, I just wanted to say this is something that will be very helpful for a lot of people and will allow me to more easily test out KDE based distros with my full setup and that is so awesome to have that possibility now.

I couldn't find a way to contact you outside of the issues so I am sorry for pinging you in the issues for a non-issue but anyway thanks again.

**Comment by Prayag2** [comment]
Oh my god, I'm soo happy that you commented! Your videos are awesome! Thanks for the kind words! I'll keep on improving it.
