### ISSUE TITLE
Order of listed profiles

### ISSUE THREAD

**Issue by kAlvaro** [Prayag2/konsave#67]
Are profiles listed in any particular order?

```shell
$ konsave -l
Konsave profiles:
ID      NAME
1       alvaro-20221130_080810
2       alvaro-20221125_080803
3       alvaro-20221213_090958
4       alvaro-20221128_090926
5       alvaro-20221130_070734
```

In this example, the latest profile is shown right in the middle (nr. 3).

**Comment by Prayag2** [comment]
The order in which the profiles are listed is determined by the `os.listdir()` function in Python. I can, however, make it print in alphabetical order.

**Comment by kAlvaro** [comment]
Not sure what order would be more useful for most people (alphabetical or creation time) but directory order is definitively not especially helpful.
