### ISSUE TITLE
Doesn't seem to work on Endeavor when installed via pip

### ISSUE THREAD

**Issue by Ryder17z** [Prayag2/konsave#69]
**Describe the bug**
Seems to install normally but the tool cannot be found after install. 
If installed under root, it will not export anything as the file.knsv does not get created and there is no error messages

**To reproduce**
Install Endeavor, install konsave, attempt to use it and fail?

**Expected behavior**
throw error messages or create the file.knsv

**Screenshots**
N/A

**System information**
 - OS or Linux distribution: Endeavor
 - How did you install Konsave? pip
 - What version of Konsave are you using? Did you try updating? 
2.1.2. / fresh install.

**Additional context**
Endeavor is running inside a Qemu VM.

**Comment by Prayag2** [comment]
Check if `konsave` exists in `~/.local/bin/`. If it does, you need to add it to PATH.

**Comment by Ryder17z** [comment]
That issue keeps popping out at random points. That's the solution, yes. (konsave appears to be working now)

_Pretty annoying having to search the web each time I encounter it because it's rare enough that i forget._
