### ISSUE TITLE
Clear current profile and revert to default/fresh KDE install

### ISSUE THREAD

**Issue by brhellman** [Prayag2/konsave#7]
Would it be possible to also make an option to wipe the current profile settings, which would the get recreated at next login?  This would give you the ability to start fresh with a default profile after a major KDE update or if you just wanted to get back to a stock profile quickly.

Thanks for your work.

**Comment by Prayag2** [comment]
I'm sorry, but could you please elaborate your question?

**Comment by brhellman** [comment]
I think it would be nice to have an optional flag you could pass to konsave that would delete/clear all profile settings vs saving them.  So the inverse of what it does now.  From a post I found this: 
`Logout from KDE and run:
cd ~/
rm -rf .kde
rm -rf .cache/plasmashell*
rm -rf .cache/org.kde.dirmodel-qml.kcache
rm -rf .cache/kioexec/ .cache/krunner/ .cache/ksycoca5*
rm -rf .cache/krunnerbookmarkrunnerfirefoxdbfile.sqlite
rm -f .config/plasma*
rm -rf .config/kde*
cd .local/
rm -rf kate/ kded5/ klipper/ knewstuff3/ kscreen/ konsole/ kwalletd/ ksysguard/ kmail2/ kcookiejar/ kactivitymanagerd/
cd share/
rm -rf dolphin kate kcookiejar kded5 keyrings klipper kmail2 knewstuff3 konsole kscreen ksysguard kwalletd kxmlgui5 plasma_engine_comic plasma plasma_notes org.kde.gwenview
cd ~/.config/
rm -rf akonadi* KDE kconf_updaterc baloo* dolphinrc drkonqirc gwenviewrc kmail2rc k*rc katemetainfos`

**Comment by Prayag2** [comment]
I think I could create an option `-w` which would stand for "wipe" and it would take a backup of the current config files and delete them. For that I would have to introduce some new functions and rewrite some stuff. It will take some time but I'll do it soon! Thanks!

**Comment by ben2talk** [comment]
Better still the ability to choose a number and overwrite a specific slot. 

Sent from Yahoo Mail for iPhone


On Monday, March 1, 2021, 10:38 PM, Prayag2 <notifications@github.com> wrote:




I think I could create an option -w which would stand for "wipe" and it would take a backup of the current config files and delete them. For that I would have to introduce some new functions and rewrite some stuff. It will take some time but I'll do it soon! Thanks!
