### ISSUE TITLE
Ansible adoption

### ISSUE THREAD

**Issue by gadgieOps** [Prayag2/konsave#76]
**Describe the solution you'd like**
This is a great project and I am truly appreciative of all the work of yourself and the contributors. I am finding it somewhat difficult to integrate into my desktop automation code using ansible.

**Describe alternatives you've considered**
konsave is my alternative!

**Additional context**
 My use case is that I must repeatedly spin up/down VMs with a KDE desktop on demand from our users. I use ansible to make sure that all of the users account information and permissions are correctly set as well ensure security patches and applications are installed. KDE wise, we set some basic shortcuts and desktop layouts. A much nicer solution would be to create an ansible role to achieve this. Konsave is functional however there are many improvements needed that I would be much more comfortable dealing with in ansible. 

I'd like to use this project as the basis of an ansible project that I will make publicly available and of course credit konsave and its authors as the initial inspiration. I would also be more than happy to continue contributing to this project as I am able to do so. Does this work ok for you?

**Comment by Prayag2** [comment]
> Does this work ok for you?

Sure! Feel free to use this anywhere :)
