### ISSUE TITLE
Instructions for a clean uninstall

### ISSUE THREAD

**Issue by why-not-try-calmer** [Prayag2/konsave#8]
Awesome tool, but please add instructions for a clean uninstall just in case.

**Comment by Prayag2** [comment]
Oh I will add that soon. For now you can run this in your terminal:
`rm ~/.local/bin/konsave; rm -r ~/.config/konsave`
This will remove the program and the config files of this program.

**Comment by why-not-try-calmer** [comment]
Thanks very much Prayag, I cultivate a strong Obsessive-compulsive order leading me pay almost no attention to programs and focus instead on licenses and uninstall instructions :D

**Comment by Prayag2** [comment]
The uninstall instructions have been updated: `python -m pip uninstall konsave`

**Comment by why-not-try-calmer** [comment]
Very kind of you, good luck for your project!
