### ISSUE TITLE
how to see profile's content ?

### ISSUE THREAD

**Issue by zeroheure** [Prayag2/konsave#87]
I think that it would help to see a profile content, because a user doesn't knows what is not saved.

I suggest to add a --show option that could either:
- display the content
- display the path to profile
- open up the file manager at the profile's path
- be a shortcut to export and directory options

And many many thanks for this great little tool I was dreaming about for years (and I should have writed it myself !)

**Comment by Prayag2** [comment]
> display the content

Displaying the content is not possible at the moment. The best I can do for that is just show the files which are backed up.

> display the path to profile
open up the file manager at the profile's path

This can be added in just a few minutes but I doubt it will be of much use as all profiles are stored in `~/.config/konsave/profiles` and you can just open that folder if you'd like to modify these profile (not recommended).

I'm glad you liked using konsave :smile:
I'm closing this issue right now but feel free to open it if you think this feature might really be useful :)
