### ISSUE TITLE
Last konsave yielded 12.5Mo .knsv file, but it's been some time it only outputs 4.0Ko .knsv files...

### ISSUE THREAD

**Issue by Ultome** [Prayag2/konsave#91]
**Describe the bug**
So as said in the title, I'm worried that it is not normal that all my new backups of mu KDE only weigh exavtly 4.0Ko...

**To reproduce**
I can't give much here, it just started to happen... I have reinstalled konsave yesterday, maybe this could help?

**Expected behavior**
I expect 15-ish Mo .knsv files to be produuced.

**System information**
 - OS or Linux distribution: onpenSUSE Tumbleweed
 - How did you install Konsave? `sudo pip3 install konsave`
 - What version of Konsave are you using? 2.2.0, on TW packages are updated daily so I must be up to date.

**Additional context**
To the developper(s): amazing job, your tool is simple, light, easy to use, and very powerful (much more than I would have thought after seeing how Plasma deals with some things). Cheers!

**Comment by Prayag2** [comment]
I'm sorry, I'm late to reply but anyways, but I guess I can close this issue. If you still face this issue, please feel free to open it again and I'll be sure to reply as soon as possible!
