### ISSUE TITLE
file exported .knsv of  1.5kb

### ISSUE THREAD

**Issue by dacorsa** [Prayag2/konsave#97]
Hi all,
i have 2 pc with kubuntu, one give a .knsv of 700mb other only of 1.5kb, is empy.
do you help me to understand why is empty?

thanks

**Comment by Prayag2** [comment]
Can you share the files to me?

**Comment by dacorsa** [comment]
yes, delete the .zip at the end
thanks
[nanokde.knsv.zip](https://github.com/Prayag2/konsave/files/12708514/nanokde.knsv.zip)

**Comment by Prayag2** [comment]
Got it. It's empty because konsave couldn't detect that you were using KDE Plasma when you first launched it. Try deleting `~/.config/konsave` and run konsave again (make sure you do it inside KDE Plasma).

**Comment by dacorsa** [comment]
ok thanks,
now works very well :)
you're a gentleman :)
